set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR xtensa)

set(TOOLCHAIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../tools/xtensa-esp-elf")

set(CMAKE_C_COMPILER   "${TOOLCHAIN_DIR}/bin/xtensa-esp32-elf-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/bin/xtensa-esp32-elf-g++")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_DIR}/bin/xtensa-esp32-elf-gcc")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)